apiVersion: v1
kind: Namespace
metadata:
  name: graduation-app
  labels:
    name: graduation-app
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    managed-by: argocd