# WEB Tier — Nginx Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: graduation-app
  labels:
    app: web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      # Affinity to spread pods across nodes and avoid co-locating with app pods & very impotant q in interviews
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: [web]
                topologyKey: kubernetes.io/hostname

      containers:
        - name: web
          #update the image tag to use the one from ECR after pushing the image in the pipeline automatically
          image: public.ecr.aws/x0m5t6i2/graduation-web:61b2ae0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu:    "50m"
            limits:
              memory: "128Mi"
              cpu:    "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds:       15
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds:       10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem:   false
            runAsNonRoot:             true
            runAsUser:                101   # nginx user